# Generated by Django 3.0.5 on 2020-11-07 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='title',
            unique_together={('name', 'year')},
        ),
    ]
