# Generated by Django 3.0.5 on 2020-11-14 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201114_2019'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='title',
            name='A rating value is valid between 1 and 10',
        ),
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
