# Generated by Django 3.0.5 on 2020-11-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201119_2207'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='api_categor_name_53a3ad_idx',
        ),
        migrations.RemoveIndex(
            model_name='genre',
            name='api_genre_name_01c28c_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(db_index=True, max_length=80, unique=True),
        ),
    ]
